name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_SCHEMA=${{ secrets.DATABASE_SCHEMA }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "AUTH_ACCESS_TOKEN_SECRET=${{ secrets.AUTH_ACCESS_TOKEN_SECRET }}" >> .env
          echo "AUTH_ACCESS_TOKEN_EXPIRATION_TIME=${{ secrets.AUTH_ACCESS_TOKEN_EXPIRATION_TIME }}" >> .env
          echo "AUTH_REFRESH_TOKEN_SECRET=${{ secrets.AUTH_REFRESH_TOKEN_SECRET }}" >> .env
          echo "AUTH_REFRESH_TOKEN_EXPIRATION_TIME=${{ secrets.AUTH_REFRESH_TOKEN_EXPIRATION_TIME }}" >> .env
          echo "R2_OBJECT_STORAGE_ACCOUNT_ID=${{ secrets.R2_OBJECT_STORAGE_ACCOUNT_ID }}" >> .env
          echo "R2_OBJECT_STORAGE_BUCKET_NAME=${{ secrets.R2_OBJECT_STORAGE_BUCKET_NAME }}" >> .env
          echo "R2_OBJECT_STORAGE_TOKEN_VALUE=${{ secrets.R2_OBJECT_STORAGE_TOKEN_VALUE }}" >> .env
          echo "R2_OBJECT_STORAGE_ACCESS_KEY_ID=${{ secrets.R2_OBJECT_STORAGE_ACCESS_KEY_ID }}" >> .env
          echo "R2_OBJECT_STORAGE_SECRET_ACCESS_KEY=${{ secrets.R2_OBJECT_STORAGE_SECRET_ACCESS_KEY }}" >> .env
          echo "PAYOS_PAYIN_CLIENT_ID=${{ secrets.PAYOS_PAYIN_CLIENT_ID }}" >> .env
          echo "PAYOS_PAYIN_API_KEY=${{ secrets.PAYOS_PAYIN_API_KEY }}" >> .env
          echo "PAYOS_PAYIN_CHECKSUM_KEY=${{ secrets.PAYOS_PAYIN_CHECKSUM_KEY }}" >> .env
          echo "PAYOS_PAYOUT_CLIENT_ID=${{ secrets.PAYOS_PAYOUT_CLIENT_ID }}" >> .env
          echo "PAYOS_PAYOUT_API_KEY=${{ secrets.PAYOS_PAYOUT_API_KEY }}" >> .env
          echo "PAYOS_PAYOUT_CHECKSUM_KEY=${{ secrets.PAYOS_PAYOUT_CHECKSUM_KEY }}" >> .env

      - name: Run compose up container
        run: docker compose -f docker-compose.yaml up --build -d
